config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :ratings
  resources :viewings

  get 'home/index'

  get 'users/index'

  get 'users/show'

  devise_for :users, controllers: { 
  	sessions: 'users/sessions',
  	registrations: 'users/registrations'

  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	has_many :viewings
	has_many :ratings
	has_many :users, through: :viewings
	belongs_to :user
	validates :name, presence: true
	validates :genre, presence: true
	validates :location, presence: true
	validates :length, presence: true
	validates :avatar, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :star, presence: true, numericality: true, inclusion: { in: 1..5 }
  validates :review, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	has_many :viewings
	has_many :ratings
	has_many :movies, through: :viewings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :movies

end

app/models/viewing.rb
class Viewing < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :liked, acceptance: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@movies = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
    @movies = current_user.movies
  end

  def create
    @movie = current_user.movies.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.json { render json: @movie, status: :created, location: @movie }
      else 
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @rating = Rating.new
    @viewing = Viewing.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :genre, :location, :length, :avatar)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
  end

  def new
    @rating = Rating.new
  end

  def create
    @rating = current_user.ratings.new(rating_params)
    respond_to do |format|
      if @rating.save
        format.json { render json: @rating, status: :created, location: @rating }
      else 
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def rating_params
    params.require(:rating).permit(:movie_id, :star, :review)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  	@user = current_user
  end
end

app/controllers/viewings_controller.rb
class ViewingsController < ApplicationController
  def index
  end

  def new
    @viewing = Viewing.new
  end

  def create
    @viewing = current_user.viewings.create(viewing_params)
      redirect_to movies_path
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def viewing_params
    params.require(:viewing).permit(:movie_id, :watched_count, :liked)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/viewings_helper.rb
module ViewingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipped</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: linear-gradient(to bottom right, black, gray);">
	<!-- Navbar -->
	<nav class="navbar sticky-top navbar-toggleable-xl navbar-inverse" style="background: linear-gradient(to top right, black, gray);">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<!-- Logo -->
			<!-- <a class="navbar-brand" href="/posts"><img src="http://cdn.playbuzz.com/cdn/cf14f63d-b744-4008-870c-7b773ac5962a/875829e7-ee1b-4e6b-b080-efd6dccd10a4.jpg" alt="Logo" style="width: 30px; height: 30px;"></a> -->

			<!-- Links -->
			<div class="collapse navbar-collapse" id="nav-content">  
				<ul class="navbar-nav">
					<li class="nav-item">
						<%= link_to "Home", root_path, class: 'nav-link' %>
					</li>
					<li class="nav-item">
						<% if user_signed_in? %>
							<%= link_to "Profile", users_show_path, class: 'nav-link' %>
						<% else %>
							<%= link_to "Profile", new_user_session_path, class: 'nav-link' %>
						<% end %>
					</li>
					<li class="nav-item">
						<%= link_to "Movies", movies_path, class: 'nav-link' %>
					</li>
				</ul>
				<span class="navbar-text">
					<% if user_signed_in? %>
						<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'sign' %>
					<% else %>
						<%= link_to "Sign up", new_user_registration_path, class: 'sign-up sign' %>
						<%= link_to "Sign in", new_user_session_path, class: 'sign' %>
					<% end %>
		    	</span>
			</div>
		</nav>
	
	
  	<p class="notice" style="color: lightgrey; margin-right: 30px"><%= notice %></p>
    <p class="alert" style="color: lightgrey; margin-right: 30px"><%= alert %></p>
    <%= yield %>
  </body>
</html>